name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Vérifier que le secret est accessible
        env:
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}
        run: |
          if [ -z "$SECRET_API_TOKEN" ]; then
            echo "❌ Le secret est vide ou inaccessible"
            exit 1
          else
            echo "✅ Le secret est bien accessible (longueur : ${#SECRET_API_TOKEN} caractères)"
          fi
          

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run job.py
        env:
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}
        run: python job.py