name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Écrire un fichier
        run: echo "Hello depuis la pipeline !" > output.txt

      - name: Upload de l'artefact
        uses: actions/upload-artifact@v4
        with:
          name: mon-fichier
          path: output.txt